data <- read.csv("./household_power_consumption.txt", sep=";", header = TRUE)
data = subset(data, Date == "1/2/2007" | Date == "2/2/2007", select = c(7,8,9))
x = 1:2880
data = cbind(x, data)
colnames(data) = c("x", "Sub1", "Sub2", "Sub3")
png("plot3.png", width = 480, height = 480, units = "px", bg = "white")
plot(data$x, data$Sub1,ylab = "Global ACtive Power (kilowatts)", xlab = "", type="l", col="black", axes = "FALSE")
legend(1900, 36, c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black","blue","red"))
par(new=TRUE)
plot(data$x, data$Sub2, type="l", ylab = "", xlab= "", col="red", axes = "FALSE", ylim = c(2,100))
par(new=TRUE)
plot(data$x, data$Sub3, type="l",  ylab = "", xlab= "", col="blue", axes = "FALSE", ylim = c(0,30))
axis(2)
axis(1, at = c(0,1440, 2880), labels = c("Thursday", "Friday", "Saturday"))
box()
dev.copy(png, file = "plot3.png") 
dev.off()
